[package]
name = "kr-pronouncer"
version = "0.1.0"
authors = ["MeSnek <sneakyfox61@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hangul = "0.1.3"
unic-ucd-hangul = "0.9.0"